Rotation based equalization
Xilinx/brevitas pull request #1061
Opened 2024-10-17 14:23 UTC by Giuseppe5

## Reason for this PR

## Changes Made in this PR

## Testing Summary

## Risk Highlight

- [ ] This PR includes code from another work (please detail).
- [ ] This PR contains API-breaking changes.
- [ ] This PR depends on work in another PR (please provide links/details).
- [ ] This PR introduces new dependencies (please detail).
- [ ] There are coverage gaps not covered by tests.
- [ ] Documentation updates required in subsequent PR.

## Checklist

- [ ] Code comments added to any hard-to-understand areas, if applicable.
- [ ] Changes generate no new warnings.
- [ ] Updated any relevant tests, if applicable.
- [ ] No conflicts with destination `dev` branch.
- [ ] I reviewed my own code changes.
- [ ] Initial CI/CD passing.
- [ ] 1+ reviews given, and any review issues addressed and approved.
- [ ] Post-review full CI/CD passing.

2024-10-20 15:16 UTC, Giuseppe5 commented on src/brevitas_examples/llm/main.py
> +    # if args.eval:
Restore

2024-10-20 15:16 UTC, Giuseppe5 commented on src/brevitas_examples/llm/main.py
> +        # apply_layernorm_affine_merge(model)
Restore

2024-10-20 15:17 UTC, Giuseppe5 commented on tests/brevitas/graph/test_equalization.py
> +# def test_resnet18_equalization():
Restore

2024-10-20 15:17 UTC, Giuseppe5 commented on src/brevitas/graph/equalize.py
> +class FunctionalNodeReference:
Still unused, maybe not needed?

2024-10-28 16:03 UTC, Giuseppe5 commented
Current limitations:
- No support for scaled_dot_product in a FX graph
- No support for MultiheadAttention
- Missing conversion from LayerNorm to RMSNorm to ensure rotation compatibility

2024-11-07 11:03 UTC, nickfraser requested changes
Could you add some basic tests for the LLM entry-point as well? Both for RMSNorm & rotations?

2024-11-07 11:03 UTC, nickfraser commented on src/brevitas_examples/llm/llm_quant/ln_affine_merge.py
> +            rms_cls, torch.nn.RMSNorm, normalized_shape=config.hidden_size, eps=config.rms_norm_eps)
torch version guard required?

2024-11-07 11:32 UTC, Giuseppe5 commented on src/brevitas/graph/equalize.py
> +def random_orthogonal_matrix(size):
Yes

2024-11-07 11:32 UTC, Giuseppe5 commented on src/brevitas_examples/llm/llm_quant/ln_affine_merge.py
> +            rms_cls, torch.nn.RMSNorm, normalized_shape=config.hidden_size, eps=config.rms_norm_eps)
Yes

2024-11-07 14:06 UTC, nickfraser commented
Other than the hadamard matrix instantiation issue, this LGTM (once above changes are applied).

2024-11-07 15:51 UTC, Giuseppe5 commented on src/brevitas_examples/llm/main.py
> +            model, guards = torch._dynamo.export(model)(**calibration_loader[0])
This has an impact on how dataloaders are created, we don't need extra kwargs for attention_mask

2024-11-13 23:22 UTC, merged