[DRAFT] Fix llm tests transformers
Xilinx/brevitas pull request #1118
Opened 2024-12-06 12:24 UTC by pablomlago

## Reason for this PR

## Changes Made in this PR

## Testing Summary

## Risk Highlight

- [ ] This PR includes code from another work (please detail).
- [ ] This PR contains API-breaking changes.
- [ ] This PR depends on work in another PR (please provide links/details).
- [ ] This PR introduces new dependencies (please detail).
- [ ] There are coverage gaps not covered by tests.
- [ ] Documentation updates required in subsequent PR.

## Checklist

- [ ] Code comments added to any hard-to-understand areas, if applicable.
- [ ] Changes generate no new warnings.
- [ ] Updated any relevant tests, if applicable.
- [ ] No conflicts with destination `dev` branch.
- [ ] I reviewed my own code changes.
- [ ] Initial CI/CD passing.
- [ ] 1+ reviews given, and any review issues addressed and approved.
- [ ] Post-review full CI/CD passing.

2024-12-06 15:09 UTC, Giuseppe5 commented on tests/brevitas_examples/test_llm.py
> +        assert_layer_types(model, exp_layer_types)
We remove completely the type check

2024-12-07 17:35 UTC, Giuseppe5 commented on tests/brevitas_examples/test_llm.py
> +                "<class 'brevitas.core.quant.int.RescalingIntQuant'>": 28,
We should only count QuantLayers

2024-12-07 17:36 UTC, Giuseppe5 commented on tests/brevitas_examples/test_llm.py
> +                "<class 'brevitas.core.quant.int.RescalingIntQuant'>": 28,
I'll let @nickfraser have the last word on these parts of the review

2024-12-09 17:33 UTC, nickfraser requested changes

2024-12-09 17:33 UTC, nickfraser commented on tests/brevitas_examples/test_llm.py
> +    args, exp_layer_types, exp_layer_types_count = layer_args
My intuition is to split this into 2 different tests, 1 which checks the types of specific layer names, another which does the layer count tests. If we want the same models / configs tested then let's be verbose about that.

2024-12-09 17:33 UTC, nickfraser commented on tests/brevitas_examples/test_llm.py
> +        assert_layer_types(model, exp_layer_types)
If it was 2 tests then this would not be required.

2024-12-09 17:33 UTC, nickfraser commented on tests/brevitas_examples/test_llm.py
> -@requires_pt_ge('2.2')
Why is this removed?

2024-12-09 17:33 UTC, nickfraser commented on tests/brevitas_examples/test_llm.py
> +from collections import defaultdict
Not used?

2024-12-09 18:21 UTC, pablomlago commented on tests/brevitas_examples/test_llm.py
> -@requires_pt_ge('2.2')
I removed it accidentally.

2024-12-11 11:12 UTC, merged