Feat (mx): unpadding during dequantization
Xilinx/brevitas pull request #1134
Opened 2024-12-18 16:58 UTC by Giuseppe5

## Reason for this PR

## Changes Made in this PR

## Testing Summary

## Risk Highlight

- [ ] This PR includes code from another work (please detail).
- [ ] This PR contains API-breaking changes.
- [ ] This PR depends on work in another PR (please provide links/details).
- [ ] This PR introduces new dependencies (please detail).
- [ ] There are coverage gaps not covered by tests.
- [ ] Documentation updates required in subsequent PR.

## Checklist

- [ ] Code comments added to any hard-to-understand areas, if applicable.
- [ ] Changes generate no new warnings.
- [ ] Updated any relevant tests, if applicable.
- [ ] No conflicts with destination `dev` branch.
- [ ] I reviewed my own code changes.
- [ ] Initial CI/CD passing.
- [ ] 1+ reviews given, and any review issues addressed and approved.
- [ ] Post-review full CI/CD passing.

2024-12-19 10:48 UTC, Giuseppe5 commented on src/brevitas/proxy/groupwise_float_parameter_quant.py
> +        shape = self.tracked_parameter_list[0].shape
We don't support weight quant sharing for groupwise anyway, so this is safe, but it is ugly.

2024-12-19 10:49 UTC, Giuseppe5 commented on src/brevitas/quant_tensor/groupwise_float_quant_tensor.py
> +        from brevitas.utils.quant_utils import groupwise_dequant
Also ugly, maybe the function should live somewhere else?

2025-01-08 16:30 UTC, nickfraser requested changes
Please check guards for the optional argument `x`. I think this can crash under certain circumstances. If there are preconditions that means that this can never occur, maybe add a comment about this.

2025-01-08 16:30 UTC, nickfraser commented on src/brevitas/proxy/groupwise_float_runtime_quant.py
> +                dequant_shape=x.shape)
Do we need to add to the clause that `x is not None`? I.e., won't this fail if `x=None`?

2025-01-08 16:30 UTC, nickfraser commented on src/brevitas/proxy/groupwise_float_runtime_quant.py
> +                x.shape)
Same here: won't this fail if `x=None` & `qt_args` is a `Tensor`?

2025-01-08 16:30 UTC, nickfraser commented on src/brevitas/proxy/float_runtime_quant.py
>              out = FloatQuantTensor(
Same here: won't this fail if `x=None` & `qt_args` is a `Tensor`?

2025-01-10 10:12 UTC, Giuseppe5 commented on src/brevitas/proxy/groupwise_float_runtime_quant.py
> +                dequant_shape=x.shape)
X is never None anymore. File runtime_quant.py, line 195 of the new file

2025-01-10 14:44 UTC, nickfraser commented on src/brevitas/proxy/groupwise_float_runtime_quant.py
> +                dequant_shape=x.shape)
Can we update the function signature to `create_quant_tensor` then? `x: GroupwiseFloatQuantTensor)` Or will this cause some other issue that I'm not seeing?

2025-01-10 14:46 UTC, nickfraser approved these changes
Approve once the function signature of `create_quant_tensor` is updated.

2025-01-11 01:26 UTC, merged