Fix UserWarning: Defining your `__torch_function__` as a plain method is deprecated and will be an error in future, please define it as a classmethod.
Xilinx/brevitas pull request #565
Opened 2023-03-28 12:29 UTC by V0XNIHILI

See: https://github.com/pytorch/pytorch/blob/08766b23de8ed50a8f52973df78114426500cb65/torch/overrides.py#L1547.

I get this error with the latest version of Brevitas (installed via `pip` one week ago) with PyTorch 1.13

2023-05-05 10:30 UTC, V0XNIHILI commented
@Giuseppe5 is this okay?

2023-05-05 15:12 UTC, Giuseppe5 requested changes

2023-05-05 15:20 UTC, Giuseppe5 commented
Apart from the change of `self` to `cls`, I don't think there are any other issues with this change.

I would wait for your commit and @volcacius comments, and eventually merge it

2025-02-26 10:24 UTC, closed without merging

2025-02-27 10:02 UTC, V0XNIHILI commented
Hi @Giuseppe5, this is still an issue today for me (using Brevitas 0.10.2). I noticed that I forgot to reply to your comment. 

Could you reopen the PR so I can finalize it?

2025-02-27 10:42 UTC, Giuseppe5 commented
I integrated this in a reticently merged PR, so on `dev` this warning shouldn't appear anymore. Sorry for closing without giving more context

2025-02-27 11:49 UTC, V0XNIHILI commented
That's great, thanks!