Generative improv
Xilinx/brevitas pull request #965
Opened 2024-05-31 12:14 UTC by Giuseppe5

2024-06-07 10:28 UTC, nickfraser requested changes
We just need a re-review of the bit related to setting the input quantization.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +    calibration_prompts = CALIBRATION_PROMPTS
Consider restructuring this.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +        if 'conv_in' in name and not args.quantize_conv_in:
Remove this if not needed.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +        if args.linear_input_bit_width is None or args.conv_input_bit_width is None:
Apply your fix and we re-review.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +            if (args.linear_input_bit_width is not None or
Fix this.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +            pipe.unet.to('cpu').to(dtype)
Check if this breaks for ONNX export.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +            export_torch_export(pipe, trace_inputs, output_dir, export_manager)
Remove this.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +        'use-ocp',
Decide if you want to keep this argument or not.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/main.py
> +    add_bool_arg(
Remove these 3 options.

2024-06-07 10:28 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/sd_quant/utils.py
> +from brevitas.export.common.handler.base import BaseHandler
Remove all of this.

2024-06-21 13:29 UTC, nickfraser requested changes

2024-06-21 13:29 UTC, nickfraser commented on src/brevitas_examples/stable_diffusion/sd_quant/export.py
> +    layer_dict['weight_zp_dtype'] = str(torch.uint8)
Should be `int8`?

2024-06-21 13:38 UTC, Giuseppe5 commented on src/brevitas_examples/stable_diffusion/sd_quant/export.py
> +    layer_dict['input_zp_dtype'] = str(torch.int8)
Restore to uint8

2024-06-21 15:19 UTC, merged